# -*- coding: utf-8 -*-
"""Introduction to SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VM-4IHP8gT80m2ur1UPxVvP0vi4A9OCN

Support Vector Machine
"""

import sklearn
from sklearn import datasets
from sklearn import svm
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier

#SVM is used for classifying data to be a certain class
cancer = datasets.load_breast_cancer()

print(cancer.feature_names)
print()
print(cancer.target_names)

x = cancer.data
y = cancer.target

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size = 0.2) 

print(x_train, y_train) #0 = malignant, 1 = benign
classes = ['malignant', 'benign ']

#implement svc, support vector classification
#c is soft margin
classifier = svm.SVC(kernel="linear", C=2)
classifier.fit(x_train, y_train)

y_prediction = classifier.predict(x_test)

accuracy = metrics.accuracy_score(y_test, y_prediction) * 100

print("Accuracy is: " + str(round(accuracy, 2)) + "%")